# Generated by Django 5.2.16 on 2026-07-09 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('variant_sku', models.CharField(db_index=True, max_length=64)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_name'], name='reviews_rev_product_4373b3_idx'), models.Index(fields=['status', 'created_at'], name='reviews_rev_status_c24b9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'variant_sku'), name='unique_review_per_user_variant_sku')],
            },
        ),
    ]
